Update pre-commit

diff --git a/.github/hooks/pre-commit b/.github/hooks/pre-commit
--- a/.github/hooks/pre-commit
+++ b/.github/hooks/pre-commit
@@ -1,6 +1,6 @@
 #!/bin/bash
-# Impide commits si hay archivos .log
-if git ls-files *.log; then
-  echo "Error: No se permiten archivos .log en el commit"
+# Verifica si index.html está presente
+if ! git diff --cached --name-only | grep -q "index.html"; then
+  echo "Error: El archivo index.html no está incluido en este commit."
   exit 1
 fi
